version: "3.8"

services:
  kafka:
    image: bitnami/kafka:3.7
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes

  account-service:
    build:
      context: .
      dockerfile: app/account/Dockerfile
    image: saga-account:latest
    container_name: account-service
    ports:
      - "8081:8081"
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka

  ledger-service:
    build:
      context: .
      dockerfile: app/ledger/Dockerfile
    image: saga-ledger:latest
    container_name: ledger-service
    ports:
      - "8082:8082"
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka

  transfer-service:
    build:
      context: .
      dockerfile: app/transfer/Dockerfile
    image: saga-transfer:latest
    container_name: transfer-service
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - account-service
      - ledger-service
      - kafka
